# This workflow will do a clean installation of node dependencies, cache/
# restore them, build the source code and run tests across different versions
# of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Continuous Integration

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      postgres:
        image: postgres
        env:
          VITE_APP_SUPABASE_URL: ${{ secrets.VITE_APP_SUPABASE_URL }}
          VITE_APP_SUPABASE_KEY: ${{ secrets.VITE_APP_SUPABASE_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set environment variables
        run: |
          echo "VITE_APP_SUPABASE_URL=${{ secrets.VITE_APP_SUPABASE_URL }}" >> $GITHUB_ENV
          echo "VITE_APP_SUPABASE_KEY=${{ secrets.VITE_APP_SUPABASE_KEY }}" >> $GITHUB_ENV

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
